### ISSUE TITLE
check why @everyone when creating a review thread to be claimed doesn't cause red notif

### ISSUE THREAD

**Issue by ziyadm** [ziyadm/test-bot-repo#137]
for the reviewer

**Comment by ghost** [comment]
looked into this a bit, i think it only gives you a notification if you're "in the thread", which i think happens when you go into it and actually type something. kinda defeats the purpose of doing @everyone -- maybe we should just add all reviewers into the thread when we make it?

**Comment by ghost** [comment]
left in code comment too, solution was to add all reviewers to the thread by @mentioning them and then immediately deleting the message so it doesnt get noisy. fixed and released
